name: Build + Publish

on:
  push:
    branches: post-ld

jobs:
  set-version:
    runs-on: ubuntu-20.04
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Bump version and tag
        id: bump
        uses: jaumann/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: version
      - name: Push commit and tag
        run: git push && git push --tags
  build:
    runs-on: ubuntu-20.04
    needs: set-version
    strategy:
      matrix:
        platform:
          - name: "windows"
            output: "LD50.exe"
          - name: "linux"
            output: "LD50.x86_64"
          - name: "mac"
            output: "LD50.zip"
          - name: "web"
            output: "index.html"
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.set-version.output.new_tag }}
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
        env:
          GODOT_VERSION: 3.4.2
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.platform.name }}
          godot -v --export ${{ matrix.platform.name}}  ./build/${{ matrix.platform.name }}/${{ matrix.platform.output }}
      - name: Deploy to Itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.platform.name }}
          ITCH_GAME: the-bimbles-vs-the-inevitable-forces-of-tedium
          ITCH_USER: tfinch
          PACKAGE: build/${{ matrix.platform.name }}
